/*
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

// Code generated by mapcomments; DO NOT EDIT.
package internal

func CommentMap() map[string]string {
	return map[string]string{}
}
